### PR TITLE
updated description and generated codemeta file

### PR DESCRIPTION
**Pull request by graceli8**
Added applicationCategory (DataAccess), ORCID identifier for author (Scott Chamberlain), and keywords (as advised by Scott) to DESCRIPTION file. Generated codemeta.json file from updated DESCRIPTION by running write_codemeta()

### CODE REVIEW

**Comment by cboettig** [comment]
@sckott This all looks good to me, will leave it to you to check over and merge.  

@graceli8 nice work, and thanks for catching the issue with the GitHub url detection when running on a fork.

**Comment by sckott** [comment]
thanks @graceli8 ! 

just saw tweet https://twitter.com/AchimZeileis/status/917319708713668608 

> Add @ORCID_Org iDs to your #rstats pkg: person(... comment = c(ORCID = "<iD>")) in DESCRIPTION/Authors@R and CRAN will generate icon/link.

is that the way or the way @graceli8  has done it here?

**Comment by cboettig** [comment]
@sckott I think you're referring to that missing `http`, right?  Yeah, that's probably necessary.  Really nice to see CRAN has adopted this, I'm not sure the genesis of that change but wonder if Kurt was inspired by codemetar; we've been pushing that as a 'hack' way to add ORCID ids in CRAN, and it looks like they have now adopted it officially!  very exciting.  See https://github.com/codemeta/codemetar/pull/33/files

**Comment by sckott** [comment]
sorry, no, that in that tweet, the form he gave was `comment = c(ORCID = "")` vs here we have `comment = ""`

**Comment by cboettig** [comment]
@sckott ah, I didn't see that, I should have read more carefully.  Yeah, his is obviously more general but I think either should work with `codemetar`, since in R it is just getting the value of the comment field.... lemme test...

**Comment by sckott** [comment]
i imagine the `codemeta.json` file needs to be put in `.Rbuildignore`?

**Comment by cboettig** [comment]
@sckott Yup, good point.  `write_codemeta()` should do that automatically but maybe it tripped up or wasn't committed? 

@graceli8 can you add `codemeta.json` to `.Rbuildignore`?

**Comment by sckott** [comment]
great, thanks @graceli8 and @cboettig

**Pull request merged**
